general.import = [ "~/.config/alacritty/alacritty-macchiato.toml", ]

[terminal.shell]
program = "zsh"

[env]
TERM = "xterm-256color"

[cursor]
style = "Block"

[window]
padding = { x = 10, y = 10}
dynamic_padding = false
decorations = "None"
opacity = 0.90

[font]
size = 12.0

[terminal]

