general.import = [ "~/.config/alacritty/alacritty-macchiato.toml", ]

[terminal.shell]
program = "zsh"

[env]
TERM = "xterm-256color"

[cursor]
style = "Block"

[window]
padding = { x = 20, y = 20}
dynamic_padding = false
decorations = "Buttonless"
opacity = 0.95

[font]
size = 12.0

[terminal]

